[project]
name = "store-sales-fake-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=40.1.2",
    "faker-commerce>=1.0.4",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "streamlit>=1.52.2",
]
